default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQLUSER'] || 'root' %>
  password: <%= ENV['MYSQLPASSWORD'] || 'AwfbIvAWOYOYSgyxHphHjeDeMKUgnFwv' %>
  host: <%= ENV['MYSQLHOST'] || ENV['RAILWAY_PRIVATE_DOMAIN'] %>
  port: <%= ENV['MYSQLPORT'] || 3306 %>
  database: <%= ENV['MYSQLDATABASE'] || 'railway' %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] || 'railway' %>
